feat: Add edit and delete post feature
Naman-Saxena1/Socioztron-Social_Media pull request #5
Opened 2022-04-25 13:15 UTC by Naman-Saxena1

2022-04-25 16:44 UTC, bhtibrewal requested changes
Code is good, changes required on the UI 
UI suggestions: 
- I don't find the use of home icon in the header when home is already there in sidebar, 
- I don't think it would good to give logout button like a CTA button  in the header, instead it would be better if you give it in the sidebar.
- It doesn't makes sense in the first place to give user the option to edit/delete when he can't as it's not his post. Instead there should be other options like bookmark post ,etc.
- it takes up a lot of place if you show all the comments on the post there itself, you can show all on a single post page 

Great work on the comments and reply but there is one issue that the input field doesn't clear the instant user clicks enter, instead after the comment is posted so i ended up clicking enter multiple times, so fix this, also there is no button to post comment the comment along side the input field so how will it work on mobile

2022-04-25 16:44 UTC, bhtibrewal commented on src/components/EditPostModal/EditPostModal.css
> +    z-index: var(--zindex-edit-post-modal);
Appreciation: it's nice you have used variable for z-index

2022-04-25 16:44 UTC, bhtibrewal commented on src/components/EditPostModal/EditPostModal.jsx
> +    const dispatch = useDispatch()
Suggestion: it would better if you name it more specifically

2022-04-25 16:44 UTC, bhtibrewal commented on src/components/UserPost/UserPost.css
> +    box-shadow: 0 0 1px black;
Suggestion: use var for color for consistency, also you shouldn't use complete black or white anywhere

2022-04-25 16:44 UTC, bhtibrewal commented on src/components/UserPost/UserPost.css
> +    font-size: 12px;
shouldn't you be using em here for font-size, because if in case the root font size changes this will stay at 12px

2022-04-25 16:44 UTC, bhtibrewal commented on src/components/UserPost/UserPost.jsx
> +    const deleteUserPost = async() => {
Suggestion: you should move these functions to a seperate file

2022-04-25 17:09 UTC, yaswanthmyneni approved these changes
the code is good, you can merge.

2022-04-25 17:09 UTC, yaswanthmyneni commented on src/components/EditPostModal/EditPostModal.css
> +    padding: 0 0 0 2rem;
suggestion: can give just padding-left here

2022-04-26 12:40 UTC, Naman-Saxena1 commented on src/components/UserPost/UserPost.css
> +    box-shadow: 0 0 1px black;
Done

2022-04-26 12:41 UTC, Naman-Saxena1 commented on src/components/UserPost/UserPost.css
> +    font-size: 12px;
Done

2022-04-26 12:44 UTC, Naman-Saxena1 commented on src/components/EditPostModal/EditPostModal.css
> +    padding: 0 0 0 2rem;
Done

2022-04-26 12:50 UTC, Naman-Saxena1 commented
> Code is good, changes required on the UI UI suggestions:
> 
> * I don't find the use of home icon in the header when home is already there in sidebar,
> * I don't think it would good to give logout button like a CTA button  in the header, instead it would be better if you give it in the sidebar.
> * It doesn't makes sense in the first place to give user the option to edit/delete when he can't as it's not his post. Instead there should be other options like bookmark post ,etc.
> * it takes up a lot of place if you show all the comments on the post there itself, you can show all on a single post page
> 
> Great work on the comments and reply but there is one issue that the input field doesn't clear the instant user clicks enter, instead after the comment is posted so i ended up clicking enter multiple times, so fix this, also there is no button to post the comment along side the input field so how will it work on mobile

1. Home button was for Login and Signup page where sidebar is not present. Thanks for pointing out, removed it from other pages.
2. Sure, will change that when I create user profile feature and profile page
3. Thanks for pointing out, removed edit/delete feature from posts that are from other users
4. Yeah, I will do that when I make single post page like twitter implementation, this is temporary
5. Thanks for pointing out issue with comments and replies, refactored code and added "Send" button to add comment/reply rather than enter key press.

Thanks for giving detailed review 😄

2022-04-26 13:07 UTC, merged